# Generated by Django 4.2 on 2024-03-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_managers_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyamount',
            name='date_selected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
