# Generated by Django 4.2 on 2024-03-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_weeklyamount_date_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyamount',
            name='date_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
