# Generated by Django 4.2 on 2024-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_weeklyamount_date_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='number_of_weeks',
            field=models.IntegerField(default=52),
        ),
    ]
