# Generated by Django 4.2 on 2024-08-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customuser_registration_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_method',
        ),
    ]
