# Generated by Django 4.2 on 2024-08-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
